pipelines:
  docker-dotnet-ide:
    group: liget
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - verify:
          elastic_profile_id: w.c2.m2048.e20
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks verify
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e20
          artifacts:
            - build:
                source: "image/imagerc*"
                destination:
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks git_tag
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks trigger_dockerhub
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks wait_all
      - itest:
          clean_workspace: true
          jobs:
            stretch:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc-stretch
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one stretch
            bionic:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc-bionic
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one bionic
            full:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc-full
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one full
            alpine:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc-alpine
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one alpine
